name: Deploy Website to Azure Container Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker Image to ACR
      run: |
        az acr login --name <YourRegistryName>
        docker build -t <YourRegistryName>.azurecr.io/your-website:latest .
        docker push <YourRegistryName>.azurecr.io/your-website:latest

    - name: Deploy to Azure Container Instance
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: <YourResourceGroup>
        template: ./azuredeploy.json
        parameters: >
          containerImage=<YourRegistryName>.azurecr.io/your-website:latest
          containerGroupName=myWebsiteContainerGroup
          location=eastus
