name: Deploy Website to Azure Container Instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Check if ACR exists
      id: acr-check
      run: |
        az acr show --name ${{ secrets.ACR_NAME }} --resource-group myrg2024 || echo "ACR_NOT_FOUND" > result.txt
        if [[ -f result.txt ]]; then echo "ACR not found, creating..."; else echo "ACR found, skipping creation."; fi
        cat result.txt

    - name: Create Azure Container Registry (ACR) if not exists
      run: |
        if [[ -f result.txt && $(cat result.txt) == "ACR_NOT_FOUND" ]]; then
          echo "Creating Azure Container Registry..."
          az acr create --name ${{ secrets.ACR_NAME }} --resource-group myrg2024 --sku Basic --admin-enabled true
        fi

    - name: Build and Push Docker Image to ACR
      run: |
        az acr login --name ${{ secrets.ACR_NAME }}
        docker build -t ${{ secrets.ACR_NAME }}.azurecr.io/mywebsite:latest .
        docker push ${{ secrets.ACR_NAME }}.azurecr.io/mywebsite:latest

    - name: Deploy to Azure Container Instance
      run: |
        az container create \
          --resource-group myrg2024 \
          --name myWebsiteContainer \
          --image ${{ secrets.ACR_NAME }}.azurecr.io/mywebsite:latest \
          --cpu 1 \
          --memory 1.5 \
          --ip-address Public \
          --ports 80 \
          --registry-login-server ${{ secrets.ACR_NAME }}.azurecr.io \
          --registry-username ${{ secrets.REGISTRY_USERNAME }} \
          --registry-password ${{ secrets.REGISTRY_PASSWORD }}

    - name: Verify Deployment
      run: |
        echo "Website deployed successfully!"
