name: Deploy to Azure ACI

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Log in to Azure CLI
    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Log in to Azure Container Registry
    - name: Log in to ACR
      run: az acr login --name ${{ secrets.ACR_NAME }}

    # Build and push Docker image to ACR
    - name: Build and Push Docker Image
      run: |
        az acr build --registry ${{ secrets.ACR_NAME }} --image myapp:latest .

    # Deploy using ARM Template
    - name: Deploy to ACI
      run: |
        az deployment group create \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --template-file azuredeploy.json \
          --parameters \
            acrName=${{ secrets.ACR_NAME }} \
            containerGroupName=mycontainergroup \
            containerName=myapp \
            imageName=myapp:latest \
            acrLoginServer=${{ secrets.ACR_NAME }}.azurecr.io
